// Generated by IcedCoffeeScript 1.3.3d
(function() {
  var courses, removedCourses, selectedCourse, student;

  student = null;

  courses = null;

  removedCourses = [];

  selectedCourse = null;

  $(document).ready(function() {
    var socket, validateSlots;
    socket = io.connect();
    socket.on("connect", function() {
      return $("#blockerbox").css({
        display: "none"
      });
    });
    $("#login_button").click(function() {
      return socket.emit("login", {
        username: $("#username_input").val(),
        password: $("#password_input").val()
      }, function(data) {
        if (data.error != null) return alert("Invalid Username/Password");
        student = data.student;
        return socket.emit("courses", {
          studentId: student.id
        }, function(data) {
          var cid, course, i, section, _i, _j, _len, _len1, _ref;
          courses = data.courses;
          $("#newcourse_select").html("");
          for (i = _i = 0, _len = courses.length; _i < _len; i = ++_i) {
            course = courses[i];
            $("#newcourse_select").append("<option nbr='" + (course.number.split(" ").join("_")) + "'>" + course.number + ": " + course.name + "</option>");
          }
          $("#newcourse_select").removeAttr("disabled");
          cid = $("#newcourse_select").children(":selected").attr("nbr").split("_").join(" ");
          selectedCourse = course = _(courses).select(function(x) {
            return x.number === cid;
          })[0];
          $("#section_select").html("");
          _ref = course.sections;
          for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
            section = _ref[_j];
            $("#section_select").append("<option>" + section.number + "</option>");
          }
          return $("#section_select, #addcourse_button").removeAttr("disabled");
        });
      });
    });
    $("#newcourse_select").change(function() {
      var cid, course, section, _i, _len, _ref;
      cid = $(this).children(":selected").attr("nbr").split("_").join(" ");
      selectedCourse = course = _(courses).select(function(x) {
        return x.number === cid;
      })[0];
      $("#section_select").html("");
      _ref = course.sections;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        section = _ref[_i];
        $("#section_select").append("<option>" + section.number + "</option>");
      }
      return $("#section_select, #addcourse_button").removeAttr("disabled");
    });
    $("#section_select").change(function() {
      return $("#addcourse_button").removeAttr("disabled");
    });
    $("#addcourse_button").click(function() {
      var cid, course, i, section, slot, slots, tcourse, _i, _j, _k, _len, _len1, _len2, _ref;
      tcourse = selectedCourse;
      cid = parseInt($("#section_select").children(":selected").text());
      slots = selectedCourse.sections[cid - 1].timetableSlots;
      for (_i = 0, _len = slots.length; _i < _len; _i++) {
        slot = slots[_i];
        $("#c" + slot.day + slot.hour).append("<div>" + selectedCourse.number + "</div>");
      }
      validateSlots();
      $("#selcourses").append("<tr><td>" + selectedCourse.number + "</td><td>" + selectedCourse.name + "</td><td>" + cid + "</td><td><button>X</button></td></tr>");
      $("#selcourses td button").last().click(function() {
        var course, i, section, _j, _k, _l, _len1, _len2, _len3, _ref;
        for (_j = 0, _len1 = slots.length; _j < _len1; _j++) {
          slot = slots[_j];
          $(_($("#c" + slot.day + slot.hour).children()).select(function(x) {
            return $(x).text() === tcourse.number;
          })[0]).remove();
        }
        $(this).parent().parent().remove();
        removedCourses = _(removedCourses).select(function(x) {
          return x !== tcourse;
        });
        courses.push(tcourse);
        $("#newcourse_select").html("");
        for (i = _k = 0, _len2 = courses.length; _k < _len2; i = ++_k) {
          course = courses[i];
          $("#newcourse_select").append("<option nbr='" + (course.number.split(" ").join("_")) + "'>" + course.number + ": " + course.name + "</option>");
        }
        $("#section_select").html("");
        $("#addcourse_button, #section_select").attr({
          disabled: "disabled"
        });
        validateSlots();
        if ($("#newcourse_select").children().length > 0) {
          cid = $("#newcourse_select").children(":selected").attr("nbr").split("_").join(" ");
          tcourse = course = _(courses).select(function(x) {
            return x.number === cid;
          })[0];
          $("#section_select").html("");
          _ref = course.sections;
          for (_l = 0, _len3 = _ref.length; _l < _len3; _l++) {
            section = _ref[_l];
            $("#section_select").append("<option>" + section.number + "</option>");
          }
          return $("#section_select, #addcourse_button").removeAttr("disabled");
        }
      });
      removedCourses.push(tcourse);
      courses = _(courses).difference(removedCourses);
      $("#newcourse_select").html("");
      for (i = _j = 0, _len1 = courses.length; _j < _len1; i = ++_j) {
        course = courses[i];
        $("#newcourse_select").append("<option nbr='" + (course.number.split(" ").join("_")) + "'>" + course.number + ": " + course.name + "</option>");
      }
      $("#section_select").html("");
      $("#addcourse_button, #section_select").attr({
        disabled: "disabled"
      });
      if ($("#newcourse_select").children().length > 0) {
        cid = $("#newcourse_select").children(":selected").attr("nbr").split("_").join(" ");
        selectedCourse = course = _(courses).select(function(x) {
          return x.number === cid;
        })[0];
        $("#section_select").html("");
        _ref = course.sections;
        for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
          section = _ref[_k];
          $("#section_select").append("<option>" + section.number + "</option>");
        }
        return $("#section_select, #addcourse_button").removeAttr("disabled");
      }
    });
    return validateSlots = function() {
      var flag, i, j, _i, _j;
      flag = true;
      for (i = _i = 1; _i <= 5; i = ++_i) {
        for (j = _j = 1; _j <= 9; j = ++_j) {
          $("#c" + i + j).css({
            backgroundColor: $("#c" + i + j).children().length > 1 ? "red" : "white"
          });
          if ($("#c" + i + j).children().length > 1) flag = false;
        }
      }
      return $("submit_button").attr({
        disabled: flag ? "" : "disabled"
      });
    };
  });

}).call(this);
